package com.wielabs.thewitness.util

object Constants {
    val africanCountries = mapOf(
        "dz" to "Algeria",
        "ao" to "Angola",
        "bw" to "Botswana",
        "bi" to "Burundi",
        "cm" to "Cameroon",
        "cv" to "Cape Verde",
        "cf" to "Central African Republic",
        "td" to "Chad",
        "km" to "Comoros",
        "yt" to "Mayotte",
        "cg" to " Republic of the congo",
        "cd" to "Democratic Republic of the congo",
        "bj" to "Benin",
        "gq" to "Equatorial Guinea",
        "et" to "Ethiopia",
        "er" to "Eritrea",
        "dj" to "Djibouti",
        "ga" to "Gabon",
        "gm" to "Gambia",
        "gh" to "Ghana",
        "gn" to "Guinea",
        "ci" to "Cote d'Ivoire",
        "ke" to "Kenya",
        "ls" to "Lesotho",
        "lr" to "Liberia",
        "ly" to "Libyan Arab Jamahiriya",
        "mg" to "Madagascar",
        "mw" to "Malawi",
        "ml" to "Mali",
        "mr" to "Mauritania",
        "mu" to "Mauritius",
        "ma" to "Morocco",
        "mz" to "Mozambique",
        "na" to "Namibia",
        "ne" to "Niger",
        "ng" to "Nigeria",
        "gw" to "Guinea-Bissau",
        "re" to "Reunion",
        "rw" to "Rwanda",
        "sh" to "Saint Helena",
        "st" to "Sao Tome and Principe",
        "sn" to "Senegal, Republic of",
        "sc" to "Seychelles",
        "sl" to "Sierra Leone",
        "so" to "Somalia",
        "za" to "South Africa",
        "zw" to "Zimbabwe",
        "ss" to "South Sudan",
        "eh" to "Western Sahara",
        "sd" to "Sudan",
        "sz" to "Swaziland",
        "tg" to "Togo",
        "tn" to "Tunisia",
        "ug" to "Uganda",
        "eg" to "Egypt",
        "tz" to "Tanzania",
        "bf" to "Burkina Faso",
        "zm" to "Zambia",
    )

    val antarcticaCountries =
        mapOf(
            "aq" to "Antarctica",
            "bv" to "Bouvet Island",
            "gs" to "South Georgia and the South Sandwich Islands",
            "tf" to "French Southern Territories",
            "hm" to "Heard Island and McDonald Islands",
        )

    val asianCountries = mapOf(
        "af" to "Afghanistan",
        "az" to "Azerbaijan",
        "bh" to "Bahrain",
        "bd" to "Bangladesh",
        "am" to "Armenia",
        "bt" to "Bhutan",
        "io" to "British Indian Ocean Territory",
        "bn" to "Brunei",
        "mm" to "Myanmar",
        "kh" to "Cambodia",
        "lk" to "Sri Lanka",
        "cn" to "China",
        "tw" to "Taiwan",
        "cx" to "Christmas Island",
        "cc" to "Cocos",
        "cy" to "Cyprus",
        "ge" to "Georgia",
        "ps" to "Palestinian Territory",
        "hk" to "Hong Kong",
        "in" to "India",
        "id" to "Indonesia",
        "ir" to "Iran",
        "iq" to "Iraq",
        "il" to "Israel",
        "jp" to "Japan",
        "kz" to "Kazakhstan",
        "jo" to "Jordan",
        "kp" to "Korea",
        "kr" to "Korea",
        "kw" to "Kuwait",
        "kg" to "Kyrgyzstan",
        "la" to "Laos",
        "lb" to "Lebanon",
        "mo" to "Macao",
        "my" to "Malaysia",
        "mv" to "Maldives",
        "mn" to "Mongolia",
        "om" to "Oman",
        "np" to "Nepal",
        "pk" to "Pakistan",
        "ph" to "Philippines",
        "tl" to "Timor-Leste",
        "qa" to "Qatar",
        "ru" to "Russian Federation",
        "sa" to "Saudi Arabia",
        "sg" to "Singapore",
        "vn" to "Vietnam",
        "sy" to "Syrian Arab Republic",
        "tj" to "Tajikistan",
        "th" to "Thailand",
        "ae" to "United Arab Emirates",
        "tr" to "Turkey",
        "tm" to "Turkmenistan",
        "uz" to "Uzbekistan",
        "ye" to "Yemen",
    )

    val europeanCountries = mapOf(
        "al" to "Albania",
        "ad" to "Andorra",
        "az" to "Azerbaijan",
        "at" to "Austria",
        "am" to "Armenia",
        "be" to "Belgium",
        "ba" to "Bosnia and Herzegovina",
        "bg" to "Bulgaria",
        "by" to "Belarus",
        "hr" to "Croatia",
        "cy" to "Cyprus",
        "cz" to "Czech Republic",
        "dk" to "Denmark",
        "ee" to "Estonia",
        "fo" to "Faroe Islands",
        "fi" to "Finland",
        "ax" to "Ã…land Islands",
        "fr" to "France",
        "ge" to "Georgia",
        "de" to "Germany",
        "gi" to "Gibraltar",
        "gr" to "Greece",
        "va" to "Holy See",
        "hu" to "Hungary",
        "is" to "Iceland",
        "ie" to "Ireland",
        "it" to "Italy",
        "kz" to "Kazakhstan",
        "xk" to "Kosovo",
        "lv" to "Latvia",
        "li" to "Liechtenstein",
        "lt" to "Lithuania",
        "lu" to "Luxembourg",
        "mt" to "Malta",
        "mc" to "Monaco",
        "md" to "Moldova",
        "me" to "Montenegro",
        "nl" to "Netherlands",
        "no" to "Norway",
        "pl" to "Poland",
        "pt" to "Portugal",
        "ro" to "Romania",
        "ru" to "Russian Federation",
        "sm" to "San Marino",
        "rs" to "Serbia",
        "sk" to "Slovakia",
        "si" to "Slovenia",
        "es" to "Spain",
        "sj" to "Svalbard & Jan Mayen Islands",
        "se" to "Sweden",
        "ch" to "Switzerland",
        "tr" to "Turkey",
        "ua" to "Ukraine",
        "mk" to "Macedonia",
        "gb" to "United Kingdom",
        "gb-eng" to "England",
        "gb-wls" to "Wales",
        "gb-nir" to "Northern Ireland",
        "gb-sct" to "Scotland",
        "gg" to "Guernsey",
        "je" to "Jersey",
        "im" to "Isle of Man",
    )

    val northAmericanCountries = mapOf(
        "ag" to "Antigua and Barbuda",
        "bs" to "Bahamas",
        "bb" to "Barbados",
        "bm" to "Bermuda",
        "bz" to "Belize",
        "vg" to "British Virgin Islands",
        "ca" to "Canada",
        "ky" to "Cayman Islands",
        "cr" to "Costa Rica",
        "cu" to "Cuba",
        "dm" to "Dominica",
        "do" to "Dominican Republic",
        "sv" to "El Salvador",
        "gl" to "Greenland",
        "gd" to "Grenada",
        "gp" to "Guadeloupe",
        "gt" to "Guatemala",
        "ht" to "Haiti",
        "hn" to "Honduras",
        "jm" to "Jamaica",
        "mq" to "Martinique",
        "mx" to "Mexico",
        "ms" to "Montserrat",
        "cw" to "CuraÃ§ao",
        "aw" to "Aruba",
        "sx" to "Sint Maarten",
        "bq" to "Bonaire",
        "ni" to "Nicaragua",
        "um" to "United States",
        "pa" to "Panama",
        "pr" to "Puerto Rico",
        "bl" to "Saint Barthelemy",
        "kn" to "Saint Kitts and Nevis",
        "ai" to "Anguilla",
        "lc" to "Saint Lucia",
        "mf" to "Saint Martin",
        "pm" to "Saint Pierre and Miquelon",
        "vc" to "Saint Vincent and the Grenadines",
        "tt" to "Trinidad and Tobago",
        "tc" to "Turks and Caicos Islands",
        "us" to "United States of America",
        "vi" to "United States Virgin Islands",
    )

    val southAmericanCountries = mapOf(
        "ar" to "Argentina",
        "bo" to "Bolivia",
        "br" to "Brazil",
        "cl" to "Chile",
        "co" to "Colombia",
        "ec" to "Ecuador",
        "fk" to "Falkland Islands",
        "gf" to "French Guiana",
        "gy" to "Guyana",
        "py" to "Paraguay",
        "pe" to "Peru",
        "sr" to "Suriname",
        "uy" to "Uruguay",
        "ve" to "Venezuela",
    )

    val australianCountries = mapOf(
        "as" to "American Samoa",
        "au" to "Australia",
        "sb" to "Solomon Islands",
        "ck" to "Cook Islands",
        "fj" to "Fiji",
        "pf" to "French Polynesia",
        "ki" to "Kiribati",
        "gu" to "Guam",
        "nr" to "Nauru",
        "nc" to "New Caledonia",
        "vu" to "Vanuatu",
        "nz" to "New Zealand",
        "nu" to "Niue",
        "nf" to "Norfolk Island",
        "mp" to "Northern Mariana Islands",
        "fm" to "Micronesia",
        "mh" to "Marshall Islands",
        "pw" to "Palau",
        "pg" to "Papua New Guinea",
        "pn" to "Pitcairn Islands",
        "tk" to "Tokelau",
        "to" to "Tonga",
        "tv" to "Tuvalu",
        "wf" to "Wallis and Futuna",
        "ws" to "Samoa",
    )
}